{% set name = "bio" %}
{% set version = "2.0.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: a22dc8ca52562cf621e0224c7b69b40b68366e3c832af25861f3fa2583e6a83b

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: {{ name }}-{{ version }}/COPYING
  summary: BioRuby is an open source Ruby library for developing bioinformatics software.
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/bioruby/{{ name }}ruby

extra:
  recipe-maintainers:
    - kozo2
    - sodre
