travis:
  secure:
    BINSTAR_TOKEN: hnEWawRA+w3bGAPrclPZg+pYIFDkVvYHV5FvGv55aicLsFUbYIKRzfYsGnE7OCWsL7q82FnzPGOS16SU4eOO0xo2zLKFcLTvgH5aHhJz7YeH7MOChvXWpJxSg0zq5dchnP9925qjEIo00aQcwuswjseWWExIgPx9A/1A918bexj5ZVNy0NGVhoyrjfbXSmD65Ec+XwwRxR15p9LYUw7ZimW56IStUNW3Xn1Hs3QuLi5SlUbnutgZtpzMsN08cKMeTyV8McfzpUzjgxyoNXmNfd9PuUdkJjE/0eSGLbCUZj65wUCT6VyV7l9TrRrgyg4QJN+fFGumYiXwHoaJtBa5vvrr536rGIHYqp1Ftp+N0xxWRHNlH3l81dfP6u3GC6s/J5+xsr8AjOzISNUxtDet+ZK6tUb/eIl+xSkbwrX58YoZx0pSXNWFDC7DlFMcpvIAli++3n21PnvFimZxTRydAP7XaU73LivNaRLCM3o5fkc6MpghH9JTcMOmXJh/HiUoieskAfrEbbt+UBUarBeAOueq0PsDZPCQc+cOheneIjdmwmopqwGqFbFNiuvUnqohlQfP1nnRdGpwhO6WY217aNZgtWbi0LDrsw+rReGZLrd68iixOlG3gkSm8YApU+8GLfCMfH9+14a8HIRmaQ0q4qh8bZuBqsIFlH4YE95aAlg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
